import { Suspense } from "react";

// Este componente pode ser usado para capturar erros na renderização
function ErrorBoundary({ children }) {
  return (
    <div>
      {/* Seu componente de fallback para erro */}
      {children}
    </div>
  );
}

export const metadata = {
  title: "SAPed - Criar Chamado",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Suspense fallback={<div>Carregando...</div>}>
          <ErrorBoundary>
            <main>{children}</main>
          </ErrorBoundary>
        </Suspense>
      </body>
    </html>
  );
}
