export const metadata = {
  title: "SAPed - Criar Chamado",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body>
      <main>{children}</main>
    </body>
  );
}
